# Generated by Django 3.2.15 on 2022-10-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0094_increase_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('success', 'success'), ('failed', 'failed'), ('running', 'running'), ('locked', 'locked'), ('aborted', 'aborted')], max_length=16),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('success', 'success'), ('failed', 'failed'), ('running', 'running'), ('locked', 'locked'), ('aborted', 'aborted')], max_length=16),
        ),
    ]
