# Generated by Django 3.2.15 on 2022-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0095_JobStatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototypeconfig',
            name='type',
            field=models.CharField(
                choices=[
                    ('string', 'string'),
                    ('text', 'text'),
                    ('password', 'password'),
                    ('secrettext', 'secrettext'),
                    ('json', 'json'),
                    ('integer', 'integer'),
                    ('float', 'float'),
                    ('option', 'option'),
                    ('variant', 'variant'),
                    ('boolean', 'boolean'),
                    ('file', 'file'),
                    ('secretfile', 'secretfile'),
                    ('list', 'list'),
                    ('map', 'map'),
                    ('structure', 'structure'),
                    ('group', 'group'),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='stageprototypeconfig',
            name='type',
            field=models.CharField(
                choices=[
                    ('string', 'string'),
                    ('text', 'text'),
                    ('password', 'password'),
                    ('secrettext', 'secrettext'),
                    ('json', 'json'),
                    ('integer', 'integer'),
                    ('float', 'float'),
                    ('option', 'option'),
                    ('variant', 'variant'),
                    ('boolean', 'boolean'),
                    ('file', 'file'),
                    ('secretfile', 'secretfile'),
                    ('list', 'list'),
                    ('map', 'map'),
                    ('structure', 'structure'),
                    ('group', 'group'),
                ],
                max_length=16,
            ),
        ),
    ]
