services:
  adcm:
    build:
      context: .
    restart: always
    volumes:
      - ${DATA_DIR}:/adcm/data
    ports:
      - 8000:8000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      POSTGRES_ADCM_PASS: ${POSTGRES_ADCM_PASS}
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
