[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py310']
include = '\.py$'
exclude = '''
(
    | \.git
    | \.venv
    | __pycache__
    | data
    | docs
    | os
    | spec
    | build
    | dist
)
'''

[tool.isort]
profile = "black"
src_paths = ["python"]
skip_glob = ["python/ansible/plugins"]
skip = ["python/init_db.py", "python/task_runner.py", "python/backupdb.py", "python/job_runner.py",
    "python/drf_docs.py"]

[tool.pylint.master]
ignore = ["migrations"]

[tool.pylint."messages control"]
disable = ["abstract-method", "consider-using-with", "fixme", "import-error", "invalid-name", "missing-docstring",
    "missing-timeout", "no-else-return", "no-member", "too-few-public-methods", "too-many-arguments", "unused-argument",
    "wrong-import-order"]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.similarities]
min-similarity-lines = 30
